mysql:
  user: root
  pwd: root
  host: 47.94.87.121
  port: 3306
  dbname: magic_space
video:
  path: /usr/local/nginx/html/video
email:
  user: magic_space_leo@163.com
  pwd: LLKZPTUFPETNUWDY
  host: smtp.163.com
  port: 465
host:
  name: www.mcspace.icu
  port: 4010